# Generated by Django 5.0.7 on 2024-07-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('created_at', models.IntegerField()),
                ('created_by', models.CharField(max_length=100)),
            ],
        ),
    ]
